/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    projects: Project;
    'learning-outcomes': LearningOutcome;
    technologies: Technology;
    courses: Course;
    organisations: Organisation;
    media: Media;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'learning-outcomes': LearningOutcomesSelect<false> | LearningOutcomesSelect<true>;
    technologies: TechnologiesSelect<false> | TechnologiesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    organisations: OrganisationsSelect<false> | OrganisationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout: (HeroBlock | RichTextBlock | MediaBlock | ColumnsBlock | CallToActionBlock | ProjectsBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * The page stays reachable, but drops out of the sitemap and gets a noindex tag.
     */
    noindex?: boolean | null;
  };
  /**
   * Decides where the page sits in the URL.
   */
  parent?: (number | null) | Page;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Derived from the slug and the parent page.
   */
  path?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  heading: string;
  intro?: string | null;
  image?: (number | null) | Media;
  /**
   * Two buttons at most; more stops reading as a choice.
   */
  links?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'mailto' | 'tel' | 'download') | null;
          reference?: (number | null) | Page;
          url?: string | null;
          mailto?: string | null;
          tel?: string | null;
          media?: (number | null) | Media;
          /**
           * Optional. Makes the link jump to a section; a block gets its anchor under Layout → Anchor.
           */
          anchor?: string | null;
          newTab?: boolean | null;
          label: string;
          appearance?: ('default' | 'outline' | 'plain') | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Letters, numbers and dashes only. A link can jump here with #anchor.
   */
  anchor?: string | null;
  background?: ('none' | 'light' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what the image shows. Required for images: screen readers and Google Images need it.
   */
  alt?: string | null;
  /**
   * Optional. Shown under the image when the block supports it.
   */
  caption?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional. Letters, numbers and dashes only. A link can jump here with #anchor.
   */
  anchor?: string | null;
  background?: ('none' | 'light' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  /**
   * Leave empty to use the caption from the media file itself.
   */
  caption?: string | null;
  width?: ('content' | 'full') | null;
  /**
   * Optional. Letters, numbers and dashes only. A link can jump here with #anchor.
   */
  anchor?: string | null;
  background?: ('none' | 'light' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnsBlock".
 */
export interface ColumnsBlock {
  columns?:
    | {
        heading?: string | null;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Letters, numbers and dashes only. A link can jump here with #anchor.
   */
  anchor?: string | null;
  background?: ('none' | 'light' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'columns';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  heading: string;
  text?: string | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'mailto' | 'tel' | 'download') | null;
          reference?: (number | null) | Page;
          url?: string | null;
          mailto?: string | null;
          tel?: string | null;
          media?: (number | null) | Media;
          /**
           * Optional. Makes the link jump to a section; a block gets its anchor under Layout → Anchor.
           */
          anchor?: string | null;
          newTab?: boolean | null;
          label: string;
          appearance?: ('default' | 'outline' | 'plain') | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Letters, numbers and dashes only. A link can jump here with #anchor.
   */
  anchor?: string | null;
  background?: ('none' | 'light' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callToAction';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectsBlock".
 */
export interface ProjectsBlock {
  heading?: string | null;
  intro?: string | null;
  source?: ('featured' | 'all' | 'kind') | null;
  kind?: ('school' | 'work' | 'side') | null;
  /**
   * Leave empty to show everything that matches.
   */
  limit?: number | null;
  showLinkToOverview?: boolean | null;
  /**
   * Optional. Letters, numbers and dashes only. A link can jump here with #anchor.
   */
  anchor?: string | null;
  background?: ('none' | 'light' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'projects';
}
/**
 * One document per project, whether it is school, work or side. The overview lives at /projects; each project gets /projects/<slug>.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Decides which section of /projects it lands in.
   */
  kind: 'school' | 'work' | 'side';
  /**
   * Tells a visitor whether the demo link is still worth clicking.
   */
  projectStatus: 'in-progress' | 'completed' | 'shipped' | 'archived';
  /**
   * One line on the card. Keep it short so cards stay the same height — the longer version goes in the summary.
   */
  tagline?: string | null;
  /**
   * The opening paragraph of the project page.
   */
  summary?: string | null;
  /**
   * Carries the card. A project without one looks unfinished.
   */
  cover?: (number | null) | Media;
  /**
   * Drives chronological sorting and the timeline.
   */
  startDate?: string | null;
  /**
   * Leave empty if the project is still running.
   */
  endDate?: string | null;
  /**
   * For example "Full-stack developer" or "Tech lead".
   */
  role?: string | null;
  /**
   * Including yourself. 1 renders as "solo project".
   */
  teamSize?: number | null;
  course?: (number | null) | Course;
  /**
   * The employer, client or school this project belongs to.
   */
  organisation?: (number | null) | Organisation;
  /**
   * Everything you actually worked with. Powers filtering by technology.
   */
  techStack?: (number | Technology)[] | null;
  /**
   * What needed solving, and for whom. Skipping straight to the tech loses the reader.
   */
  problem?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * How you tackled it: research, choices made, trade-offs.
   */
  approach?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Your part, separate from the team’s. Both assessors and recruiters ask this first on group work.
   */
  myContribution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * What came of it — shipped, handed over, graded, abandoned. Honest beats impressive.
   */
  outcome?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional deep dive below the story: screenshots, diagrams, a long write-up.
   */
  layout?: (HeroBlock | RichTextBlock | MediaBlock | ColumnsBlock | CallToActionBlock | ProjectsBlock)[] | null;
  /**
   * Repository, live demo, report, design file.
   */
  links?:
    | {
        label: string;
        type: 'repo' | 'demo' | 'report' | 'design' | 'video' | 'package' | 'article' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Screenshots with captions. The caption is the argument — an uncaptioned screenshot proves nothing.
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * What this shows, and why it matters.
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Reports, assessment forms, advisory documents.
   */
  documents?:
    | {
        file: number | Media;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * What this project proves, and where. Each entry shows up under its outcome on /learning-outcomes.
   */
  learningOutcomes?:
    | {
        outcome: number | LearningOutcome;
        level?: ('1' | '2' | '3' | '4') | null;
        /**
         * Point at something concrete in this project. Link to the commit, the document, the decision.
         */
        evidence?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * What went well, what you would do differently next time.
   */
  reflection?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Quotes from a teacher, client or teammate. Far stronger evidence than self-assessment, and almost nobody includes it.
   */
  feedback?:
    | {
        source: string;
        sourceRole?: string | null;
        quote: string;
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    noindex?: boolean | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Use this for work under an NDA.
   */
  visibility: 'public' | 'anonymised' | 'on-request';
  /**
   * Shown instead of the organisation, for example "a logistics company".
   */
  clientAlias?: string | null;
  /**
   * Featured projects lead the homepage.
   */
  featured?: boolean | null;
  /**
   * Lowest first within its section. Equal values fall back to newest first.
   */
  sortOrder?: number | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Modules and semesters you can attach to a school project. Replaces the hard-coded dropdown, so adding one no longer needs a deploy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  /**
   * For example "S7". Used to order the study timeline.
   */
  semester?: string | null;
  institution?: string | null;
  description?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Employers, clients and schools you can attach to a project.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations".
 */
export interface Organisation {
  id: number;
  name: string;
  type: 'employer' | 'client' | 'school';
  logo?: (number | null) | Media;
  url?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * The stack you pick per project. Keeping these as documents instead of free text is what makes "everything I built with React" possible.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies".
 */
export interface Technology {
  id: number;
  name: string;
  /**
   * Groups the technology on the skills overview.
   */
  category: 'language' | 'framework' | 'database' | 'infrastructure' | 'tooling' | 'design';
  /**
   * Optional. Square, transparent background works best.
   */
  logo?: (number | null) | Media;
  url?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * The outcomes you are assessed on, in your programme’s own wording. Projects link to these, which is what lets /learning-outcomes list the evidence per outcome.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-outcomes".
 */
export interface LearningOutcome {
  id: number;
  /**
   * Short handle, for example "LO1".
   */
  code: string;
  title: string;
  /**
   * One or two lines, used on cards and the overview.
   */
  shortDescription?: string | null;
  /**
   * Paste the exact text from your programme so assessors recognise it.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional. What each level means for this outcome.
   */
  levels?:
    | {
        level: '1' | '2' | '3' | '4';
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Lowest first, so LO1 stays above LO2.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Points an old path at a new one. Only consulted when no page exists at the old path.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'learning-outcomes';
        value: number | LearningOutcome;
      } | null)
    | ({
        relationTo: 'technologies';
        value: number | Technology;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'organisations';
        value: number | Organisation;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        columns?: T | ColumnsBlockSelect<T>;
        callToAction?: T | CallToActionBlockSelect<T>;
        projects?: T | ProjectsBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        noindex?: T;
      };
  parent?: T;
  generateSlug?: T;
  slug?: T;
  path?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  image?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              reference?: T;
              url?: T;
              mailto?: T;
              tel?: T;
              media?: T;
              anchor?: T;
              newTab?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  anchor?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  anchor?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  caption?: T;
  width?: T;
  anchor?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColumnsBlock_select".
 */
export interface ColumnsBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        heading?: T;
        content?: T;
        id?: T;
      };
  anchor?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              reference?: T;
              url?: T;
              mailto?: T;
              tel?: T;
              media?: T;
              anchor?: T;
              newTab?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  anchor?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectsBlock_select".
 */
export interface ProjectsBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  source?: T;
  kind?: T;
  limit?: T;
  showLinkToOverview?: T;
  anchor?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  projectStatus?: T;
  tagline?: T;
  summary?: T;
  cover?: T;
  startDate?: T;
  endDate?: T;
  role?: T;
  teamSize?: T;
  course?: T;
  organisation?: T;
  techStack?: T;
  problem?: T;
  approach?: T;
  myContribution?: T;
  outcome?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        columns?: T | ColumnsBlockSelect<T>;
        callToAction?: T | CallToActionBlockSelect<T>;
        projects?: T | ProjectsBlockSelect<T>;
      };
  links?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        file?: T;
        label?: T;
        id?: T;
      };
  learningOutcomes?:
    | T
    | {
        outcome?: T;
        level?: T;
        evidence?: T;
        id?: T;
      };
  reflection?: T;
  feedback?:
    | T
    | {
        source?: T;
        sourceRole?: T;
        quote?: T;
        date?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        noindex?: T;
      };
  generateSlug?: T;
  slug?: T;
  visibility?: T;
  clientAlias?: T;
  featured?: T;
  sortOrder?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-outcomes_select".
 */
export interface LearningOutcomesSelect<T extends boolean = true> {
  code?: T;
  title?: T;
  shortDescription?: T;
  description?: T;
  levels?:
    | T
    | {
        level?: T;
        description?: T;
        id?: T;
      };
  generateSlug?: T;
  slug?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies_select".
 */
export interface TechnologiesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  logo?: T;
  url?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  semester?: T;
  institution?: T;
  description?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations_select".
 */
export interface OrganisationsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  logo?: T;
  url?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  siteTitle?: string | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'mailto' | 'tel' | 'download') | null;
          reference?: (number | null) | Page;
          url?: string | null;
          mailto?: string | null;
          tel?: string | null;
          media?: (number | null) | Media;
          /**
           * Optional. Makes the link jump to a section; a block gets its anchor under Layout → Anchor.
           */
          anchor?: string | null;
          newTab?: boolean | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  note?: string | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'mailto' | 'tel' | 'download') | null;
          reference?: (number | null) | Page;
          url?: string | null;
          mailto?: string | null;
          tel?: string | null;
          media?: (number | null) | Media;
          /**
           * Optional. Makes the link jump to a section; a block gets its anchor under Layout → Anchor.
           */
          anchor?: string | null;
          newTab?: boolean | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  siteTitle?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              reference?: T;
              url?: T;
              mailto?: T;
              tel?: T;
              media?: T;
              anchor?: T;
              newTab?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  note?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              reference?: T;
              url?: T;
              mailto?: T;
              tel?: T;
              media?: T;
              anchor?: T;
              newTab?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null);
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}